name: Wyam2 build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_NOLOGO: true
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Project name to pack and publish
  PROJECT_NAME: Wyam2

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet 2.1
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: | 
            2.1.x
            2.2.x
            3.1.x
            5.0.x
            6.0.x
      - run: dotnet --list-sdks
      - run: dotnet --list-runtimes
      - name: Build and test
        run: ./build.ps1 -Target Run-Tests -Verbose
        shell: pwsh
