name: Sync issues to AZDO

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.AZDO_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_ACCESS_TOKEN }}"
          ado_organization: "Wyam2"
          ado_project: "wyam"
          ado_area_path: "wyam\\core"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100
