name: Wyam2 nightly build

on:
  schedule:
    - cron: '30 0 * * *'

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Project name to pack and publish
  PROJECT_NAME: Wyam2

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check last day commits that touched src or theme folders
    outputs:
      create_nightlies: ${{ steps.should_run.outputs.create_nightlies }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: check commits less than a day that had changes in src or theme folders
        id: should_run
        continue-on-error: true
        run: test $(git log --pretty="format:" --since="2 days ago" --name-only | grep -c -e '^src' -e '^themes' ) -eq 0 && echo "::set-output name=create_nightlies::false" || echo "::set-output name=create_nightlies::true"
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build and test
        run: ./build.ps1 -Target Run-Unit-Tests
        shell: pwsh
  nightly:
    needs: [check_date, build]
    if: ${{ needs.check_date.outputs.create_nightlies != 'false' }}
    runs-on: windows-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Nightly pack
        run: ./build.ps1 -Target Nightly
        shell: pwsh
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: ./build/choco/*.nupkg
