name: Wyam2 release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet 2.1
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: | 
            2.1.x
            2.2.x
            3.1.x
            5.0.x
            6.0.x
      - run: dotnet --list-sdks
      - run: dotnet --list-runtimes
      - name: Build and test
        run: ./build.ps1 -Target Run-Tests
        shell: pwsh
  release:
    needs: [build]
    runs-on: windows-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
    steps:
      - name: Get the tag name
        run: echo "GITHUB_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet 2.1
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: | 
            2.1.x
            2.2.x
            3.1.x
            5.0.x
      - run: dotnet --list-sdks
      - run: dotnet --list-runtimes
      - name: Publish release
        run: ./build.ps1 -Target Release -ScriptArgs ('--tag=${{env.GITHUB_TAG}}')
        shell: pwsh
      - name: Trigger documentation build
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: Wyam2/docs
          event-type: release
          client-payload: '{"tag": "${{ env.GITHUB_TAG }}"}'
