name: Wyam2 release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build and test
        run: ./build.ps1 -Target Run-Tests
        shell: pwsh
  release:
    runs-on: windows-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
    steps:
      - name: Get the tag name
        run: echo "GITHUB_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash
      - name: Create packages
        run: ./build.ps1 -Target Package -ScriptArgs ('--tag=${{env.GITHUB_TAG}}')
        shell: pwsh
      - name: Publish packages
        run: ./build.ps1 -Target Publish -ScriptArgs ('--tag=${{env.GITHUB_TAG}}')
        shell: pwsh
      - name: Trigger documentation build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: Wyam2/docs
          event-type: release
          client-payload: '{"tag": "${{ env.GITHUB_TAG }}"}'